./main kruskal 0 ../../../arquivos/mst/lu05.txt out.txt
./main kruskal 1 ../../../arquivos/mst/lu10.txt out.txt
./main kruskal 2 ../../../arquivos/mst/lu05.txt out.txt
./main kruskal 3 ../../../arquivos/mst/lu05.txt out.txt
./main kruskal 0 ../../../arquivos/mst/lu10.txt out.txt
./main kruskal 1 ../../../arquivos/mst/lu10.txt out.txt
./main kruskal 2 ../../../arquivos/mst/lu10.txt out.txt
./main kruskal 3 ../../../arquivos/mst/lu10.txt out.txt
./main kruskal 0 ../../../arquivos/mst/lu25.txt out.txt
./main kruskal 1 ../../../arquivos/mst/lu25.txt out.txt
./main kruskal 2 ../../../arquivos/mst/lu25.txt out.txt
./main kruskal 3 ../../../arquivos/mst/lu25.txt out.txt
./main kruskal 0 ../../../arquivos/mst/lu50.txt out.txt
./main kruskal 1 ../../../arquivos/mst/lu50.txt out.txt
./main kruskal 2 ../../../arquivos/mst/lu50.txt out.txt
./main kruskal 3 ../../../arquivos/mst/lu50.txt out.txt
./main kruskal 0 ../../../arquivos/mst/lu75.txt out.txt
./main kruskal 1 ../../../arquivos/mst/lu75.txt out.txt
./main kruskal 2 ../../../arquivos/mst/lu75.txt out.txt
./main kruskal 3 ../../../arquivos/mst/lu75.txt out.txt
./main prim 0 ../../../arquivos/mst/lu05.txt out.txt
./main prim 1 ../../../arquivos/mst/lu10.txt out.txt
./main prim 2 ../../../arquivos/mst/lu05.txt out.txt
./main prim 3 ../../../arquivos/mst/lu05.txt out.txt
./main prim 0 ../../../arquivos/mst/lu10.txt out.txt
./main prim 1 ../../../arquivos/mst/lu10.txt out.txt
./main prim 2 ../../../arquivos/mst/lu10.txt out.txt
./main prim 3 ../../../arquivos/mst/lu10.txt out.txt
./main prim 0 ../../../arquivos/mst/lu25.txt out.txt
./main prim 1 ../../../arquivos/mst/lu25.txt out.txt
./main prim 2 ../../../arquivos/mst/lu25.txt out.txt
./main prim 3 ../../../arquivos/mst/lu25.txt out.txt
./main prim 0 ../../../arquivos/mst/lu50.txt out.txt
./main prim 1 ../../../arquivos/mst/lu50.txt out.txt
./main prim 2 ../../../arquivos/mst/lu50.txt out.txt
./main prim 3 ../../../arquivos/mst/lu50.txt out.txt
./main prim 0 ../../../arquivos/mst/lu75.txt out.txt
./main prim 1 ../../../arquivos/mst/lu75.txt out.txt
./main prim 2 ../../../arquivos/mst/lu75.txt out.txt
./main prim 3 ../../../arquivos/mst/lu75.txt out.txt